{% set name = "kconfig" %}
{% set version = "5.74.0" %}
{% set major_minor = ".".join(version.split(".")[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://download.kde.org/stable/frameworks/{{ major_minor }}/kconfig-{{ version }}.tar.xz
  sha256: dfeff0649f8987f88a01827c06468b87547509d9e46920902a55f6a0d6adc5db

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('kconfig', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - extra-cmake-modules >={{ major_minor }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
  host:
    - qt >=5.11.0
    - mesalib
    - xorg-libxfixes  # [linux]
    - xorg-libxext

test:
  commands:
    - test -f ${PREFIX}/lib/libKF5ConfigCore.so

about:
  home: https://api.kde.org/frameworks/kconfig/html/index.html
  license: LGPL-v2.1-or-later
  license_family: GPL
  license_file: COPYING.LIB
  summary: Persistent platform-independent application settings.
  description: |
    KConfig provides an advanced configuration system. It is made of two parts:
    KConfigCore and KConfigGui.
  dev_url: https://cgit.kde.org/kconfig.git/tree

extra:
  recipe-maintainers:
    - scopatz
