{% set name = "kconfig" %}
{% set version = "5.81.0" %}
{% set major_minor = ".".join(version.split(".")[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://download.kde.org/stable/frameworks/{{ major_minor }}/kconfig-{{ version }}.tar.xz
  sha256: 1ddf9e384140ce72bbd555eb36a76d0db1a256391429b02b51769c08ebf0ae8f

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('kconfig', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - extra-cmake-modules >={{ major_minor }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
  host:
    - qt >=5.11.0
    - mesalib
    - xorg-libxfixes  # [linux]
    - xorg-libxext

test:
  commands:
    - test -f ${PREFIX}/lib/libKF5ConfigCore.so

about:
  home: https://api.kde.org/frameworks/kconfig/html/index.html
  license: BSD-2-Clause AND BSD-3-Clause AND GPL-2.0-or-later AND LGPL-2.0-only AND LGPL-2.0-or-later AND LGPL-2.1-only AND LGPL-3.0-only AND LicenseRef-KDE-Accepted-LGPL AND MIT
  license_file:
    - LICENSES/BSD-2-Clause.txt
    - LICENSES/BSD-3-Clause.txt
    - LICENSES/GPL-2.0-or-later.txt
    - LICENSES/LGPL-2.0-only.txt
    - LICENSES/LGPL-2.0-or-later.txt
    - LICENSES/LGPL-2.1-only.txt
    - LICENSES/LGPL-3.0-only.txt
    - LICENSES/LicenseRef-KDE-Accepted-LGPL.txt
    - LICENSES/MIT.txt
  summary: Persistent platform-independent application settings.
  description: |
    KConfig provides an advanced configuration system. It is made of two parts:
    KConfigCore and KConfigGui.
  dev_url: https://cgit.kde.org/kconfig.git/tree

extra:
  recipe-maintainers:
    - scopatz
